webtalk_init -webtalk_dir C:\\Users\\cag01\\Documents\\mdh\\vhdl\\gimme2a\\sdk_2014.4\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "fr sep 9 11:22:42 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "u0jpf2v5c1fn65asqmirisn5nm" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1473171670402" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4.1" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1473171670402"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1473171670402"
webtalk_transmit -clientid 2195057772 -regid "" -xml C:\\Users\\cag01\\Documents\\mdh\\vhdl\\gimme2a\\sdk_2014.4\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\cag01\\Documents\\mdh\\vhdl\\gimme2a\\sdk_2014.4\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\cag01\\Documents\\mdh\\vhdl\\gimme2a\\sdk_2014.4\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
